In [1]:
import numpy as np
import pandas as pd

In [16]:
with pd.ExcelFile('赛题三：疫情防控重点人群预测与画像-样例数据.xlsx') as excel:
#     用户轨迹链数据
    df1=pd.read_excel(excel,0)
#     用户对象数据
    df2=pd.read_excel(excel,1)
#     基站对象数据
    df3=pd.read_excel(excel,2)
#     北京中高风险地区数据
    df4=pd.read_excel(excel,3)
#     用户标签数据
    df5=pd.read_excel(excel,4)

In [31]:
# 按照用户id进行分类存储到list
def sorted_by_time(dataframe):
    df1_user_id_list=[]
#     根据用户id分类
    user_id_set=set(dataframe.用户标识.tolist())
    for temp_user_id_set in user_id_set:
#         根据用户id 存储到dataframe
        temp_dataframe=dataframe[dataframe.用户标识==temp_user_id_set]
#     根据业务发生时间进行排序
        temp_dataframe=temp_dataframe.sort_values(by='业务发生时间',ascending=True)
        df1_user_id_list.append(temp_dataframe)
#         返回最终结果
    return df1_user_id_list

In [33]:
df1_user_id_list=sorted_by_time(df1)

In [44]:
# 如果一个人在白天7.30到18.00 在某个lac和ci之间时间停留时长超过360分钟，说明该地方为办公点；
# 如果一个人在晚上23:00到24:00+ 白天0:00-7.30之间，停留时长超过300分钟，说明改地方为住房；

    用户标识        业务离开时间        业务发生时间  LAC                CI  停留时长
48  3802  202203010435  202203010000    4  4e952f539ab0e1ad   275
49  3802  202203010520  202203010435    4  f109c5c08a29bb65    45
70  3802  202203010720  202203010520    4  4e952f539ab0e1ad   120
71  3802  202203010725  202203010720    4  840f2b103a7b3084     5
56  3802  202203010730  202203010725    4  b6fa46bf49d642b8     5
57  3802  202203010735  202203010730    4  71268a8a02154064     5
72  3802  202203010740  202203010735    4  395f080f01019056     5
60  3802  202203011230  202203010740    4  4f5585757ad018c5   290
59  3802  202203011235  202203011230    4  ad832c675d0a0523     5
63  3802  202203011300  202203011235    4  4f5585757ad018c5    25
64  3802  202203011325  202203011300    4  ad832c675d0a0523    25
54  3802  202203011350  202203011325    4  4f5585757ad018c5    25
55  3802  202203011400  202203011350    4  ad832c675d0a0523    10
62  3802  202203011740  202203011400    4  4f5585757ad018c5   220
65  3802  202203011750  202203011740    4  c43156d4192f32ee    10
66  3802  202203011755  202203011750    4  5e7e8d43ae117215     5
67  3802  202203011800  202203011755    4  2b267d5b864e1db7     5
58  3802  202203011915  202203011800    4  f109c5c08a29bb65    75
50  3802  202203012015  202203011915    4  4e952f539ab0e1ad    60
61  3802  202203012030  202203012015    4  f109c5c08a29bb65    15
52  3802  202203012050  202203012030    4  e07aa161ec5cc7aa    20
53  3802  202203012105  202203012050    4  f109c5c08a29bb65    15
68  3802  202203012200  202203012105    4  4e952f539ab0e1ad    55
69  3802  202203012240  202203012200    4  f109c5c08a29bb65    40
51  3802  202203020000  202203012240    4  4e952f539ab0e1ad    80